favourites selection tutorial music/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'  #we mentioned app_name here. So that in when html we will use 'music:detail'. It will not be confusing cause we will know 'detail' view belong to which app and also we can use 'detail' word for another view
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),

]

main_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))

]

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'  #we mentioned app_name here. So that in when html we will use 'music:detail'. It will not be confusing cause we will know 'detail' view belong to which app and also we can use 'detail' word for another view
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),    #as_view converts classes in views.py to view
    url(r'^register/$', views.UserFromView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #/music/album/add/
    url(r'^album/add/', views.AlbumCreate.as_view(), name='album-add'), # in tutorial it was like "r'^album/add/$'" but for me it worked without $ sign
    url(r'^album/(?P<pk>[0-9]+)/', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'^album/(?P<pk>[0-9]+)/delete/', views.AlbumDelete.as_view(), name='album-delete'),

]

favourites selection tutorial music/music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.artist + "-" + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.artist + "-" + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

favourites selection tutorial music/music/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from django.shortcuts import HttpResponse


def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums': all_albums, }       #context is something that a html page need to work. It is passes to html page
    return render(request, 'music/index.html', context)  # if only one key value in context. we can simply write {'all_albums': all_albums,}


def detail(request, album_id):
    #try:                                        ## if user enters album_id that doesnt exist
     #   album = Album.objects.get(pk=album_id)
   # except Album.DoesNotExist:
    #    raise Http404("Uh oh! It happens. Album is in process of making")
    album = get_object_or_404(Album, pk=album_id) # we can use this line instead of above code
    return render(request, 'music/detail.html', {'album': album})


def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song']) #https://www.youtube.com/watch?v=irH98-4eKmQ&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK&index=24
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {'album': album,
                                                     'error_message': 'you did not select valid song'})

    else:
        selected_song.is_favourite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/views.py
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = "music/index.html"

    def get_queryset(self):     #default name when you return a list object from ListView generic function is gonna be called object_list
        return Album.objects.all()  #by default it return "object list". So even if it isnt mentioned here but you can see in index.html that we have used object_list


class DetailView(generic.DetailView):
    model = Album
    template_name = "music/detail.html"


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy("music:index")


class UserFromView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #register user
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

favourites selection tutorial music/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GlobalCitizen{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">

    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>

    {#https://www.youtube.com/watch?v=9S-jM3gpMkM    must watch to understand process flow of css#}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Header & logo Global citizen-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"><!-- "#" in topnavbar play important part without it it will not work-->
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">GlobalCitizen</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li>
                    <a href="#">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="bt btn-default">Search</button>

            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                       Add Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>

    {% block body %}
    {% endblock %}
</body>

</html>

favourites selection tutorial music/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    <img src = "{{ album.album_logo }}" style="width: 250px;">
    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    {% if error_message %}
        <strong>{{ error_message }}</strong>
    {% endif %}

    <form action = "{% url 'music:favourite' album.id %}" method = "post" >
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" >
            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}       <!--https://www.youtube.com/watch?v=irH98-4eKmQ&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK&index=24-->
                {% if song.is_favourite %}
                    <img src="https://i.stack.imgur.com/W2ct0.png" />
                {% endif %}
            </label><br>
        {% endfor %}
        <input type="submit" value="Favourite" >


    </form>
{% endblock %}

favourites selection tutorial music/music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}

    {% if all_albums %}
        <h4>Welcome to my Music</h4>
        <ul>
            {% for album in all_albums %}
                <li><a href = '{% url 'music:detail' album.id%}'>{{ album.album_title }}</a></li>  <!--Here we havent hard coded href = music/ album.id. We used music:detail checkout music/urls.py for further -->
            {% endfor %}
        </ul>
    {% else %}
        <h3>you dont have any album</h3>
    {% endif %}

{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new Album {% endblock %}
{% block albumAdd_active %}active{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel-default">
                <div class="panel-body">
                    <h3>Add a Album Here:</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GlobalCitizen{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">

    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>

    {#https://www.youtube.com/watch?v=9S-jM3gpMkM    must watch to understand process flow of css#}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Header & logo Global citizen-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"><!-- "#" in topnavbar play important part without it it will not work-->
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">GlobalCitizen</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}">
                    <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li class="{% block songs_active %}{% endblock %}">
                    <a href="#">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="bt btn-default">Search</button>

            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block albumAdd_active %}{% endblock %}">
                    <a href="{% url 'music:album-add' %} }">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                       Add Albums
                    </a>
                </li>
                <li class="{% block Logout_active %}{% endblock %}">
                    <a href="#">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>

    {% block body %}
    {% endblock %}
</body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    <img src = "{{ album.album_logo }}" style="width: 250px;">
    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" >
            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}       <!--https://www.youtube.com/watch?v=irH98-4eKmQ&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK&index=24-->
                {% if song.is_favourite %}
                    <img src="https://i.stack.imgur.com/W2ct0.png" />
                {% endif %}
            </label><br>
        {% endfor %}

{% endblock %}

music/templates/music/form-template.html
{% for fields in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ fields.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ fields.label_tag }}</label>
        <div class="col-sm-10">{{ fields }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}

        <ul>
            {% for album in object_list %}
                <li><a href = '{% url 'music:detail' album.id%}'>{{ album.album_title }}</a></li>  <!--Here we havent hard coded href = music/ album.id. We used music:detail checkout music/urls.py for further -->
            {% endfor %}
        </ul>






{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register {% endblock %}

{% block body %}

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}